### ISSUE TITLE
[ECOSYSTEM CHALLENGE] Using Remix And MetaMask On Moonbeam

### ISSUE THREAD

**Issue by albertov19** [Timidan/Poladot-Remix-Metamask#1]
Hi Timidan,

Thanks for your submission in our challenge. Unfortunately, you provided the ERC20 token contract address as the checkContract address so our checks have failed for your submission. Could you please check this problem? You can resubmit your submission by answering in this issue post.

Regards,
Alberto

**Comment by Timidan** [comment]
0x2DcAE33d5c92cD0CAb15C2Ac0C1b79F552eF242a

Apologies, Here is the correct address

**Comment by Timidan** [comment]
Did it work?

**Comment by albertov19** [comment]
Yes :) congrats

**Comment by Timidan** [comment]
Thanks a lot

Wanted to ask a question about other challenges...especially the ones including plasm nodes....Do i have to run a local node to do them ?

Reason is because i am having a lot of problem building it over here even with all requirements and rust dependencies installed...this is really pulling me back as i intend to finish 18 or more challenges

any help would be appreciated

**Comment by albertov19** [comment]
Sorry Timidan, this challenge is by another group so feel free to reach them out directly ;)

**Comment by Timidan** [comment]
Oh...got it..Thanks

**Comment by Timidan** [comment]
sorry to pop in again...has payments been sent out for this bounty?

**Comment by albertov19** [comment]
Hey Timidan,

We are in the process of issuing the payments. Between today and tomorrow they should be paid.

Regards
Alberto
